"""Outreach and reply domain models.

Spec: spec/product/02-architecture.md — Domain models / Lead pipeline models
Spec: spec/product/03-db-schema.md — messages, replies tables
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel

from zer0.domain.config import Channel, ResolvedConfig


class MessageStatus(str, Enum):
    drafted = "drafted"
    pending_approval = "pending_approval"
    approved = "approved"
    rejected = "rejected"
    sent = "sent"


class Sentiment(str, Enum):
    positive = "positive"
    neutral = "neutral"
    negative = "negative"


class OutreachDraft(BaseModel):
    """Generated by draft_outreach tool. Not yet sent."""

    lead_id: str
    campaign_id: str
    tenant_id: str
    channel: Channel
    subject: str | None = None  # email only
    body: str
    personalisation_notes: str
    config_snapshot: ResolvedConfig  # immutable snapshot of config that drove this draft
    sequence_number: int = 1  # 1 = first touch, 2+ = follow-ups


class SentMessage(OutreachDraft):
    """An OutreachDraft that has been successfully delivered."""

    message_id: str  # internal UUID
    sent_at: datetime
    external_message_id: str  # Gmail thread ID / WhatsApp message ID
    status: MessageStatus = MessageStatus.sent


class Reply(BaseModel):
    """An inbound reply received from a lead."""

    lead_id: str
    tenant_id: str
    message_id: str | None = None  # nullable — may not thread to a specific sent message
    channel: Channel
    content: str
    received_at: datetime
    sentiment: Sentiment | None = None  # set after classification
